spring:

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}

server:
  port: ${SERVER_PORT}

jwt:
  header: ${JWT_HEADER}
  scretKey: ${SECRET_KEY}
  accessExp: ${ACCESS_EXPIRED}
  accessTyp: ${ACCESS_TYPE}
  refreshExp: ${REFRESH_EXPIRED}
  refreshTyp: ${REFRESH_TYPE}
